CREATE TABLE country (
                         id bigint generated by default as identity primary key,
                         name VARCHAR(255) NOT NULL,
                         continent VARCHAR(255) NOT NULL
);

CREATE TABLE author (
                        id bigint generated by default as identity primary key,
                        name VARCHAR(255) NOT NULL,
                        surname VARCHAR(255) NOT NULL,
                        country_id BIGINT REFERENCES country(id)
);

CREATE TABLE book_copy (
                           id bigint generated by default as identity primary key,
                           condition smallint NOT NULL,
                           rented BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE book (
                      id bigint generated by default as identity primary key,
                      name VARCHAR(255) NOT NULL,
                      category varchar(50) NOT NULL,
                      author_id BIGINT REFERENCES author(id),
                      country_id BIGINT REFERENCES country(id)
);

CREATE TABLE book_book_copies (
                                  book_id BIGINT REFERENCES book(id),
                                  book_copies_id BIGINT REFERENCES book_copy(id),
                                  PRIMARY KEY (book_id, book_copies_id)
);

CREATE TABLE library_users (
                               username VARCHAR(255) UNIQUE PRIMARY KEY,
                               password VARCHAR(255) NOT NULL,
                               name VARCHAR(255) NOT NULL,
                               surname VARCHAR(255) NOT NULL,
                               is_account_non_expired BOOLEAN DEFAULT TRUE,
                               is_account_non_locked BOOLEAN DEFAULT TRUE,
                               is_credentials_non_expired BOOLEAN DEFAULT TRUE,
                               is_enabled BOOLEAN DEFAULT TRUE,
                               role VARCHAR(50) NOT NULL
);

CREATE TABLE wish_list (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_username VARCHAR(255) UNIQUE REFERENCES library_users(username)
);

CREATE TABLE wish_list_book_list (
                                     wish_list_id BIGINT REFERENCES wish_list(id),
                                     book_list_id BIGINT REFERENCES book(id),
                                     PRIMARY KEY (wish_list_id, book_list_id)
);